name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
      - name: Test
        run: xcodebuild clean test -project Gameformation/Gameformation.xcodeproj -scheme Gameformation -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
