name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ["platform:iOS Simulator, id:C8CD8244-A621-4923-BF8A-F2EFA9A8A603, OS:14.4, name:iPhone 12"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
      - name: Build
        run: |
          xcodebuild clean build -project Gameformation/Gameformation.xcodeproj -scheme Gameformation -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project Gameformation/Gameformation.xcodeproj -scheme GameformationTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
