name: CI-Test

on: [push]

jobs:
  build:
  
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project Gameformation/Gameformation.xcodeproj -scheme Gameformation -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" | xcpretty
      - name: Test
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean test -project Gameformation/Gameformation.xcodeproj -scheme Gameformation -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" | xcpretty
